# Generated by Django 4.2.7 on 2023-12-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_confession_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
