# Generated by Django 4.2.7 on 2023-12-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_confession_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='subject',
        ),
        migrations.AlterField(
            model_name='confession',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
