# Generated by Django 4.2.7 on 2023-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_confession_subject_alter_confession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='comments',
            field=models.JSONField(default=dict),
        ),
    ]
