# Generated by Django 4.2.7 on 2023-12-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_confession_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='comments',
        ),
    ]
