# Generated by Django 4.2.7 on 2023-12-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_confession_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='subject',
            field=models.CharField(default='Confession', max_length=255),
        ),
    ]
